theme: 'just-the-docs'
color_scheme: sia
title: 'SickleInAfrica'

exclude: [ruby]

aux_links:
  "Edit on GitHub":
    - "https://github.com/sickle-in-africa/sequence-analysis-pipelines"

plugins:
  - jekyll-target-blank